<template>
  <div class="form-group">
    <!-- @todo IDs need to be autogenerated! -->
    <div v-if="$apollo.error">ERROR</div>
    <label for="websites">Website</label>
    <input
      list="websites"
      class="form-control"
      autocomplete="off"
      :readonly="$apollo.loading"
      :placeholder="placeholder"
    />
    <datalist id="websites">
      <option
        v-for="(website) in websites"
        :key="website.id"
        :value="website.name"
      />
    </datalist>
  </div>
</template>

<script>
import gql from 'graphql-tag';

const { isArray } = Array;

export default {
  /**
   *
   */
  data() {
    return {
      websites: [],
      error: null,
    };
  },

  /**
   *
   */
  computed: {
    placeholder() {
      if (this.$apollo.loading) return 'Loading websites...';
      return 'Select a website...';
    },
  },

  /**
   *
   */
  apollo: {
    websites: {
      query: gql`
        query WebsiteSites {
          websiteSites(input: { sort: { field: name }, pagination: { limit: 100 } }) {
            edges {
              node {
                id
                name
              }
            }
          }
        }
      `,
      update({ websiteSites }) {
        if (websiteSites && isArray(websiteSites.edges)) {
          const mapped = websiteSites.edges.map(({ node }) => node);
          return mapped;
        }
        return [];
      },
      // error(e) {
      //   console.error(e);
      // },
    },
  },

  /**
   *
   */
  mounted() {
    console.log('mounted websites');
  },

  /**
   *
   */
  created() {
    console.log('created websites');
  },

  /**
   *
   */
  destroyed() {
    console.log('destroyed websites');
  },
};
</script>
