<template>
  <div>
    <div class="form-group">
      <!-- @todo IDs need to be autogenerated! -->
      <!-- @todo handle errors -->
      <label for="websites">Website</label>
      <input
        list="websites"
        class="form-control"
        autocomplete="off"
        :readonly="isLoadingWebsites"
        :placeholder="placeholder"
      />
      <datalist id="websites">
        <option
          v-for="(website) in websites"
          :key="website.id"
          :value="website.name"
        />
      </datalist>
    </div>
    <hr />
    <schedule-list :content-id="contentId" />
  </div>
</template>

<script>
import gql from 'graphql-tag';
import ScheduleList from './list.vue';
import mapNodes from '../../../utils/map-nodes';

export default {
  /**
   *
   */
  props: {
    contentId: {
      type: Number,
      required: true,
    },
  },

  /**
   *
   */
  data() {
    return {
      websites: [],
      error: null,
    };
  },

  /**
   *
   */
  components: { ScheduleList },

  /**
   *
   */
  computed: {
    isLoadingWebsites() {
      return this.$apollo.queries.websites.loading;
    },
    placeholder() {
      if (this.isLoadingWebsites) return 'Loading websites...';
      return 'Select a website...';
    },
  },

  /**
   *
   */
  apollo: {
    websites: {
      query: gql`
        query WebsiteSchedulingWebsiteSelect {
          websiteSites(input: { sort: { field: name }, pagination: { limit: 100 } }) {
            edges {
              node {
                id
                name
              }
            }
          }
        }
      `,
      update({ websiteSites }) {
        return mapNodes(websiteSites);
      },
      // error(e) {
      //   console.error(e);
      // },
    },
  },

  /**
   *
   */
  mounted() {
    console.log('mounted websites');
  },

  /**
   *
   */
  created() {
    console.log('created websites');
  },

  /**
   *
   */
  destroyed() {
    console.log('destroyed websites');
  },
};
</script>
