<template>
  <div class="autocomplete">
    <!-- @todo IDs need to be autogenerated! -->
    <!-- @todo handle errors -->
    <div class="autocomplete__input-group">
      <input
        class="autocomplete__input"
        autocomplete="off"
        v-model="phrase"
        @focus="open"
        :readonly="sectionsAreLoading"
        :placeholder="placeholder"
      />
      <div class="autocomplete__input-group-append">
        <button
          :disabled="!canClear"
          class="btn btn--icon btn--secondary-outline"
          type="button"
          @click="clear"
        >
          <icon-x />
        </button>
      </div>
    </div>

    <ul v-show="isOpen" class="autocomplete__results">
      <li
        v-if="!sectionsAreLoading && !sections.length"
        class="autocomplete__result autocomplete__result--empty"
        @click="close"
      >
        No sections found.
      </li>
      <li
        v-for="(section) in sections"
        :key="section.id"
        class="autocomplete__result"
        @click="setResult(section.fullName)"
      >
        {{ section.fullName }}
      </li>
    </ul>
  </div>
</template>

<script>
import gql from 'graphql-tag';
import IconX from '../../icons/x.vue';
import mapNodes from '../../../utils/map-nodes';

export default {
  /**
   *
   */
  data() {
    return {
      phrase: '',
      websites: [],
      error: null,
      isOpen: false,
    };
  },

  components: { IconX },

  /**
   *
   */
  computed: {
    sectionsAreLoading() {
      return this.$apollo.queries.sections.loading;
    },
    placeholder() {
      if (this.sectionsAreLoading) return 'Loading sections...';
      return 'Select a section...';
    },
    canClear() {
      return Boolean(this.phrase);
    },
  },

  /**
   *
   */
  methods: {
    open() {
      this.isOpen = true;
    },
    close() {
      this.isOpen = false;
    },
    clear() {
      this.phrase = '';
    },
    handleBlur(event) {
      if (!this.$el.contains(event.target)) this.close();
    },
    setResult(result) {
      this.phrase = result;
      this.isOpen = false;
    },
  },

  /**
   *
   */
  mounted() {
    document.addEventListener('click', this.handleBlur);
  },

  /**
   *
   */
  destroyed() {
    document.removeEventListener('click', this.handleBlur);
  },

  /**
   *
   */
  apollo: {
    sections: {
      query: gql`
        query BMCSchedulingSelectSection {
          websiteSections(input: { sort: { field: fullName, order: asc }, pagination: { limit: 0 } }) {
            edges {
              node {
                id
                fullName
                site {
                  id
                  name
                }
              }
            }
          }
        }
      `,
      update({ websiteSections }) {
        return mapNodes(websiteSections);
      },
    },
  },
};
</script>
