<template>
  <div class="autocomplete">
    <!-- @todo IDs need to be autogenerated! -->
    <!-- @todo handle errors -->
    <div class="autocomplete__input-group">
      <input
        class="autocomplete__input"
        autocomplete="off"
        v-model="phrase"
        @focus="open"
        :readonly="isLoading"
        :placeholder="placeholder"
      />
      <div class="autocomplete__input-group-append">
        <button
          :disabled="!canClear"
          class="btn btn--icon btn--secondary-outline"
          type="button"
          @click="clear"
        >
          <icon-x />
        </button>
      </div>
    </div>

    <ul v-show="isOpen" class="autocomplete__results autocomplete__results--scheduling">
      <li
        v-if="!isLoading && !sections.length"
        class="autocomplete-result autocomplete-result--empty"
        @click="close"
      >
        No sections found.
      </li>
      <li
        v-for="(section) in sections"
        :key="section.id"
        :data-id="section.id"
        :data-name="section.term"
        class="autocomplete-result"
        @click="select(section)"
      >
        <span class="autocomplete-result__product-name">{{ section.site.name }}</span>
        <span class="autocomplete-result__section-name">{{ section.fullName }}</span>
      </li>
    </ul>
  </div>
</template>

<script>
import gql from 'graphql-tag';
import IconX from '../../icons/x.vue';
import mapNodes from '../../../utils/map-nodes';

export default {
  /**
   *
   */
  data() {
    return {
      phrase: '',
      websites: [],
      error: null,
      isOpen: false,
    };
  },

  components: { IconX },

  /**
   *
   */
  computed: {
    isLoading() {
      return this.$apollo.loading;
    },
    placeholder() {
      if (this.isLoading) return 'Loading sections...';
      return 'Select a section...';
    },
    canClear() {
      return Boolean(this.phrase);
    },
  },

  /**
   *
   */
  methods: {
    open() {
      this.isOpen = true;
    },
    close() {
      this.isOpen = false;
    },
    clear() {
      this.phrase = '';
    },
    handleBlur(event) {
      if (!this.$el.contains(event.target)) this.close();
    },
    select(section) {
      this.phrase = section.fullName;
      this.isOpen = false;
    },
  },

  /**
   *
   */
  mounted() {
    document.addEventListener('click', this.handleBlur);
  },

  /**
   *
   */
  destroyed() {
    document.removeEventListener('click', this.handleBlur);
  },

  /**
   *
   */
  apollo: {
    sections: {
      query: gql`
        query BMCSchedulingSelectSection {
          websiteSites(input: { sort: { field: name, order: asc }, pagination: { limit: 0 } }) {
            edges {
              node {
                id
                name
                sections(input: { sort: { field: fullName, order: asc }, pagination: { limit: 0 } }) {
                  edges {
                    node {
                      id
                      fullName
                    }
                  }
                }
              }
            }
          }
        }
      `,
      update({ websiteSites }) {
        const websites = mapNodes(websiteSites);
        return websites.reduce((arr, site) => {
          const sections = mapNodes(site.sections)
            .map(section => ({ ...section, site: { id: site.id, name: site.name }, term: `${site.name}: ${section.fullName}` }));
          arr.push(...sections);
          return arr;
        }, []);
      },
    },
  },
};
</script>
