<template>
  <div class="autocomplete">
    <!-- @todo IDs need to be autogenerated! -->
    <!-- @todo handle errors -->
    <div class="input-group">
      <input
        class="autocomplete__input"
        autocomplete="off"
        v-model="phrase"
        @focus="open"
        :readonly="websitesAreLoading"
        :placeholder="placeholder"
      />
      <div class="input-group-append">
        <button class="btn btn--icon btn--secondary-outline" type="button" id="button-addon2">
          <icon-x />
        </button>
      </div>
    </div>

    <ul v-show="isOpen" class="autocomplete__results">
      <li
        v-for="(website) in websites"
        :key="website.id"
        class="autocomplete__result"
        @click="setResult(website.name)"
      >
        {{ website.name }}
      </li>
    </ul>
  </div>
</template>

<script>
import gql from 'graphql-tag';
import IconX from '../../icons/x.vue';
import mapNodes from '../../../utils/map-nodes';

export default {
  /**
   *
   */
  data() {
    return {
      phrase: '',
      websites: [],
      error: null,
      isOpen: false,
    };
  },

  components: { IconX },

  /**
   *
   */
  computed: {
    websitesAreLoading() {
      return this.$apollo.queries.websites.loading;
    },
    placeholder() {
      if (this.websitesAreLoading) return 'Loading websites...';
      return 'Select a website...';
    },
  },

  /**
   *
   */
  methods: {
    open() {
      this.isOpen = true;
    },
    close() {
      this.isOpen = false;
    },
    handleBlur(event) {
      if (!this.$el.contains(event.target)) this.close();
    },
    setResult(result) {
      this.phrase = result;
      this.isOpen = false;
    },
  },

  /**
   *
   */
  apollo: {
    websites: {
      query: gql`
        query WebsiteSchedulingWebsiteSelect {
          websiteSites(input: { sort: { field: name }, pagination: { limit: 100 } }) {
            edges {
              node {
                id
                name
              }
            }
          }
        }
      `,
      update({ websiteSites }) {
        return mapNodes(websiteSites);
      },
    },
  },

  /**
   *
   */
  mounted() {
    console.log('mounted websites');
    document.addEventListener('click', this.handleBlur);
  },

  /**
   *
   */
  created() {
    console.log('created websites');
  },
};
</script>
